name: Lint ModOrganizer 2

on:
  # Automatic triggers
  push:
  pull_request:
    types: [opened, synchronize, reopened]
  # Manual trigger - allows users to manually start the linting from GitHub Actions UI
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check format
        uses: ModOrganizer2/check-formatting-action@master
        with:
          check-path: "."
          exclude-regex: "third-party"
